Feat/upsert profile
Xchange-Taiwan/X-Career-User pull request #4
Opened 2024-11-17 11:42 UTC by TerrenceChao

2024-12-01 14:06 UTC, TerrenceChao commented
@ymtech2004 育志有空再幫忙看下，謝謝

2024-12-03 13:42 UTC, thenamecouldbeLiu requested changes

2024-12-03 13:42 UTC, thenamecouldbeLiu commented on src/config/conf.py
我有在rds上開了一個db 連線資訊有佈在lambda了
.env如下
DB_HOST=x-career-db-test.cu7knbzuvltn.ap-northeast-1.rds.amazonaws.com
DB_PORT=5432
DB_USER=postgres
DB_PASSWORD=postgres
DB_NAME=postgres
DB_SCHEMA=x-career-dev

conf.py新增如下
DB_HOST = os.getenv('DB_HOST', 'localhost')
DB_PORT = os.getenv('DB_PORT', '5432')
DB_USER = os.getenv('DB_USER', 'user_connection')
DB_PASSWORD = os.getenv('DB_PASSWORD', 'pg_user_password')
DB_NAME = os.getenv('DB_NAME', 'x-career')
DB_SCHEMA = os.getenv('DB_SCHEMA', 'Xchange_local')

2024-12-03 15:36 UTC, TerrenceChao commented
.env如下
DB_HOST=x-career-db-test.cu7knbzuvltn.ap-northeast-1.rds.amazonaws.com
DB_PORT=5432
DB_USER=postgres
DB_PASSWORD=postgres
DB_NAME=postgres
DB_SCHEMA=x-career-dev

conf.py新增如下
DB_HOST = os.getenv('DB_HOST', 'localhost')
DB_PORT = os.getenv('DB_PORT', '5432')
DB_USER = os.getenv('DB_USER', 'user_connection')
DB_PASSWORD = os.getenv('DB_PASSWORD', 'pg_user_password')
DB_NAME = os.getenv('DB_NAME', 'x-career')
DB_SCHEMA = os.getenv('DB_SCHEMA', 'Xchange_local')

On Tue, Dec 3, 2024 at 9:42 PM 劉育志 ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> On src/config/conf.py
> <https://github.com/Xchange-Taiwan/X-Career-User/pull/4#discussion_r1867743616>
> :
>
> 我有在rds上開了一個db 連線資訊有佈在lambda了
> .env如下
> DB_HOST=x-career-db-test.cu7knbzuvltn.ap-northeast-1.rds.amazonaws.com
> DB_PORT=5432
> DB_USER=postgres
> DB_PASSWORD=postgres
> DB_NAME=postgres
> DB_SCHEMA=x-career-dev
>
> conf.py新增如下
> DB_HOST = os.getenv('DB_HOST', 'localhost')
> DB_PORT = os.getenv('DB_PORT', '5432')
> DB_USER = os.getenv('DB_USER', 'user_connection')
> DB_PASSWORD = os.getenv('DB_PASSWORD', 'pg_user_password')
> DB_NAME = os.getenv('DB_NAME', 'x-career')
> DB_SCHEMA = os.getenv('DB_SCHEMA', 'Xchange_local')
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Xchange-Taiwan/X-Career-User/pull/4#pullrequestreview-2475716860>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACJQS5NDAZPIHDPXCQJNQWT2DWYN3AVCNFSM6AAAAABR53FCICVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDINZVG4YTMOBWGA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-12-03 15:38 UTC, merged